class AttackTypes:
    GENERIC_SQL_INJECTION = "GENERIC_SQL_INJECTION"
    AUTH_BYPASS_SQL_INJECTION = "AUTH_BYPASS_SQL_INJECTION"
    TIME_BASED_SQL_INJECTION = "TIME_BASED_SQL_INJECTION"
    ERROR_BASED_SQL_INJECTION = "ERROR_BASED_SQL_INJECTION"
    PRIVILLAGE_ESCALATION = "PRIVILLAGE_ESCALATION"
    NO_SQL = "NO_SQL"
    MY_SQL = "MYSQL"
    ORACLE = "ORACLE"
    INVALIDHTTP_REQ = "INVALID_HTTP_REQ"




    
