class AttackTypes:
    GENERIC_SQL_INJECTION = "GENERIC_SQL_INJECTION"
    AUTH_BYPASS_SQL_INJECTION = "AUTH_BYPASS_SQL_INJECTION"
    TIME_BASED_SQL_INJECTION = "TIME_BASED_SQL_INJECTION"
    ERROR_BASED_SQL_INJECTION = "ERROR_BASED_SQL_INJECTION"
    
